### ISSUE TITLE
Bug in v5.0.46 - No possible to upload custom javascript to a site

### ISSUE THREAD

**Issue by aetdr** [globaleaks/globaleaks-whistleblowing-software#4392]
### What version of GlobaLeaks are you using?

v5.0.46

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Hi @evilaliv3 

When trying to upload a js file to /api/admin/files/script using the WebUI, it fails giving the following:
```

{
    "error_message": "InternalServerError [Unexpected]",
    "error_code": 1,
    "arguments": [
        "Unexpected"
    ]
}

```

**Comment by aetdr** [comment]
> ### What version of GlobaLeaks are you using?
> v5.0.46
> 
> ### What browser(s) are you seeing the problem on?
> All
> 
> ### What operating system(s) are you seeing the problem on?
> Windows
> 
> ### Describe the issue
> Hi [@evilaliv3](https://github.com/evilaliv3)
> 
> When trying to upload a js file to /api/admin/files/script using the WebUI, it fails giving the following:
> 
> ```
> 
> {
>     "error_message": "InternalServerError [Unexpected]",
>     "error_code": 1,
>     "arguments": [
>         "Unexpected"
>     ]
> }
> ```
> 
> ### Proposed solution
> _No response_

css fails too, the same error

**Comment by evilaliv3** [comment]
Hello @aetdr , would you please load a copy of your /var/globaleaks/log/globaleaks.log?

I'm trying to debug the issue but i'm the moment i'm not able to reproduce the problem in any manner.

I've also implemented any missing unit tests on this handler but in a regular setup i'm not incurring in any defect.

**Comment by aetdr** [comment]
Hi @evilaliv3 

This is the server-side message that gets logged. We are on Ubuntu 20.04

```

2025-02-09 14:10:24+0100 [-] [E] Unhandled exception raised:
2025-02-09 14:10:24+0100 [-] [E] TypeError Inappropriate argument type.\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 432, in render\n    self.handler.process_file_upload()\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/base.py", line 364, in process_file_upload\n    self.state.TempUploadFiles[file_id] = SecureTemporaryFile(Settings.tmp_path)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/utils/securetempfile.py", line 20, in __init__\n    self.cipher = Cipher(ChaCha20(os.urandom(32), os.urandom(16)), mode=None)\n\nTypeError: __init__() missing 1 required positional argument: 'backend'\n
2025-02-09 14:10:24+0100 [-] Exception ignored in: <function SecureTemporaryFile.__del__ at 0x7fe7789b5b80>
2025-02-09 14:10:24+0100 [-] Traceback (most recent call last):
2025-02-09 14:10:24+0100 [-]   File "/usr/lib/python3/dist-packages/globaleaks/utils/securetempfile.py", line 105, in __del__
2025-02-09 14:10:24+0100 [-]     self.close()
2025-02-09 14:10:24+0100 [-]   File "/usr/lib/python3/dist-packages/globaleaks/utils/securetempfile.py", line 85, in close
2025-02-09 14:10:24+0100 [-]     if self.fd is not None:
2025-02-09 14:10:24+0100 [-] AttributeError: 'SecureTemporaryFile' object has no attribute 'fd'

```

**Comment by aetdr** [comment]
@evilaliv3 
And here is the mail that gets sent to admin:
```

TypeError Inappropriate argument type.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/globaleaks/rest/api.py", line 432, in render
    self.handler.process_file_upload()

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/base.py", line 364, in process_file_upload
    self.state.TempUploadFiles[file_id] = SecureTemporaryFile(Settings.tmp_path)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/securetempfile.py", line 20, in __init__
    self.cipher = Cipher(ChaCha20(os.urandom(32), os.urandom(16)), mode=None)

TypeError: __init__() missing 1 required positional argument: 'backend'
```

**Comment by evilaliv3** [comment]
Thankyou @aetdr .

Actually this defects are secondary to the problem. 

The reason of the problem is unclear. 

Today we will issue a 5.0.47, lets see if you still will encounter the problem there.

**Comment by aetdr** [comment]
Hi @evilaliv3 

I have just tested with v5.0.48
The files get uploaded with no error, so that part is solved. Thanks.

But, there is no immediate visual fedback. 
You have to refresh the page to see the change. Otherways it appears as nothing has changed.

**Comment by aetdr** [comment]
Hi @evilaliv3 

The other issue is that public anonymous web access is not working with v5.0.48:

- the initial request is sent, but nothing gets recieved - no response at all
- the javascript waiting circle is spinning and never stops
- the browsers memory usage goes to the roof, consuming gigabytes 
- as an admin of root site id=1, i can access and manage the other tenants (no problem here) 

> Hi [@evilaliv3](https://github.com/evilaliv3)
> 
> I have just tested with v5.0.48 The files get uploaded with no error, so that part is solved. Thanks.
> 
> But, there is no immediate visual fedback. You have to refresh the page to see the change. Otherways it appears as nothing has changed.

**Comment by evilaliv3** [comment]
Thank you @aetdr 

Regarding the missing feedback i will proceed checking.

Regarding the others problems please open dedicated tickets and add a link / instructions where to retest the situation or we might forget to check on the problem.

**Comment by aetdr** [comment]
Hi @evilaliv3 

I can create a new ticket, but maybe the issue is related.
If I remove the custom script, anonymous access works. It is still custom-script related.

**Comment by evilaliv3** [comment]
I see, do you mind passing me a copy of your custom script?

**Comment by aetdr** [comment]
Hi @evilaliv3 

Here is the script, nothing fancy:

```

// /#/recipient/home
GL.mockEngine.addMock('/#/recipient/home', '#UserWelcomeMessage', function(elem) {

  if (document.getElementById('CustomID') === null) {
      switch (GL.language) {

        //case 'en':
        //  break;

        default:
          elem.innerHTML = '<div id="CustomID">text</div>';
      }
    
  }

});


// PrivacyBadge
  GL.mockEngine.addMock("*", "#PrivacyBadge", function(elem) {

    switch (GL.language) {

      //case 'en':
      //  break;

      default:
        elem.innerHTML = '<div>Some text ' + scope.public.node.onionservice + '</div>';

    }
  });


```

**Comment by evilaliv3** [comment]
@aetdr : Actually with your script you are editing the html without checking if you already edited it.

Any time you edit the html we call again your mock, so you have generated and infinite loop.

you can do simply: ```return  '<div>Some text ' + scope.public.node.onionservice + '</div>';```

**Comment by aetdr** [comment]
Thank you @evilaliv3
