### ISSUE TITLE
Failure in using jedisct1/libsodium 0.8.3

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/globaleaks-whistleblowing-software#4813]
### What version of GlobaLeaks are you using?

5.0.89

### Describe the issue

Hello @jedisct1,

i tried to report on github but i noticed that intentionally or by mistake you might have restricted tickets to old contributors.
Please let me know which is your preferred way to be reported about these issues and i will follow that.

In the meantime:
at globaleaks we use libsodium for this single operation, working on 0.8.2:

```
import sodium from 'libsodium-wrappers-sumo';

async function hashArgon2(password, salt, iterations, memory) {
  const passwordBytes = sodium.from_string(password);
  const binaryString = atob(salt);
  const saltBytes = Uint8Array.from(binaryString, char => char.charCodeAt(0));
  const truncatedSalt = saltBytes.slice(0, 16);

  const hash = sodium.crypto_pwhash(
    32,
    passwordBytes,
    truncatedSalt,
    iterations,
    memory,
    sodium.crypto_pwhash_ALG_ARGON2ID13
  );

  return sodium.to_base64(hash, sodium.base64_variants.ORIGINAL);
}

self.onmessage = async function (e) {
  const { id, text, salt, iterations, memory } = e.data;

  try {
    await sodium.ready;
    const hash = await hashArgon2(text, salt, iterations, memory);
    self.postMessage({ id, success: true, result: hash });
  } catch (error) {
    self.postMessage({ id, success: false, error: error.message });
  }
};
```

we compile this with webpack and all is working well with 0.8.2.

apparently on the new version using 0.8.3 we are now getting:
```
crypto.worker.js:36 Uncaught TypeError: libsodium_sumo is not a function
    at crypto.worker.js:36:285
    at crypto.worker.js:74:12
    at webpackUniversalModuleDefinition (crypto.worker.js:7:11)
    at crypto.worker.js:10:3
(anonymous) @ crypto.worker.js:36
(anonymous) @ crypto.worker.js:74
webpackUniversalModuleDefinition @ crypto.worker.js:7
(anonymous) @ crypto.worker.js:10
```

Here a screenshot with the detail:

<img width="991" height="705" alt="Image" src="https://github.com/user-attachments/assets/1360ed3f-ef95-4e52-9fa8-82b5d4e4bac6" />

Please let me know if you need any more information.

Thank you!!

### Proposed solution (optional)

To be identified

**Comment by evilaliv3** [comment]
@jedisct1: is this related to https://github.com/jedisct1/libsodium.js/commit/af7a75bcb8df055eb7998797fc16dd014a417dbb?

**Comment by jedisct1** [comment]
Can you try this?

**Comment by evilaliv3** [comment]
Sure thing. We build from npm, is it already published or are you available to give me some tips ? thank you!

**Comment by evilaliv3** [comment]
Ah just noticed that i might probably wasp the files, lets me give it a try and i will be back to you.

**Comment by evilaliv3** [comment]
It works like a charm @jedisct1 !

**Comment by evilaliv3** [comment]
@jedisct1 : If you do not have planned short changes do you mind releaseing a 0.8.4 ? Thank you if you could!

**Comment by evilaliv3** [comment]
Issue solved with 0.8.4. Thank you! @jedisct1 !
